### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by ChanChunSong** [tytso/xfsprogs#1]
Do you ever see these error message ?

linux.c:24:10: fatal error: sys/ustat.h: No such file or directory
   24 | #include <sys/ustat.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [../include/buildrules:43: linux.lo] Error 1
make[1]: *** [include/buildrules:23: libxfs] Error 2
make: *** [Makefile:53: default] Error 2

**Comment by tytso** [comment]
This xfsprogs git repository is massively old and has not been updated in a long time (2015; back before Trump was president).   See the ABOUT statement describing this repo:

> xfsprogs with local changes for ext4/android (WARNING: the master branch is frequently rewound!) --- use the upstream repo at git://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git if you want to do any development

We've since given up on trying to build xfsprogs against the Android bionic libc, as it's just missing too much to build system programs.   The current approach for building xfstests for Android is to build using Debian Arm64, and then using a debian chroot.  See:  https://thunk.org/android-xfstests

This is why this repo is essentially abandoned.  The only reason why it still exists is for GPL compliance.
